### ISSUE TITLE
11.7.1 had a huge ABI break

### ISSUE THREAD

**Issue by kkraus14** [conda-forge/cuda-python-feedstock#15]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

11.7.1 had a huge ABI break that moved from redefining all of the CUDA functions in Cython to externing them: https://github.com/NVIDIA/cuda-python/commit/cfa118ab15268657597e07b318087e0e517bf726

For any library that uses the Cython parts of cuda-python, this can lead to a runtime failure if something was built with 11.7.1 and then tries to run on 11.7.0, or vice versa because the function signature changes. I.E. if built with 11.7.1 and then tried to run on 11.7.0:
```
E   TypeError: C function cuda.ccudart.cudaStreamSynchronize has wrong signature (expected cudaError_t (cudaStream_t), got __pyx_t_4cuda_7ccudart_cudaError_t (__pyx_t_4cuda_7ccudart_cudaStream_t))
```

We should probably add a repodata patch to make anything pre 11.7.1 require `<11.7.1` and anything post 11.7.1 require `>=11.7.1,<12`?

cc @jakirkham

The `rmm` packages in conda-forge are impacted by this as they're built with 11.7.1, but the `rmm` packages in the rapidsai channel are built with something older, presumably to avoid specifically this.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by leofang** [comment]
@vzhurba01 @m3vaz This impacts CUDA Python wheel users too...

**Comment by bdice** [comment]
We may want to build `rmm` on conda-forge with the 11.7.0 release for consistency with the rest of RAPIDS… this is tough. @kkraus14 or others, do you have thoughts on that?

**Comment by leofang** [comment]
It should be doable. Only RMM 22.08.0 was built with CUDA Python 11.7.1. We could mark it as broken on conda-forge, rebuild with CUDA Python 11.7.0, and set a constraint on its runtime dependency to avoid 11.7.1, if everyone is OK. But it's better if we need to discuss `rmm` issues in https://github.com/conda-forge/rmm-feedstock, not here.

**Comment by leofang** [comment]
> But it's better if we discuss `rmm` issues in https://github.com/conda-forge/rmm-feedstock, not here.

See https://github.com/conda-forge/rmm-feedstock/issues/15.

**Comment by leofang** [comment]
Made two PRs to address this issue:
- https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/325
- #17

**Comment by jakirkham** [comment]
Have been out for a few weeks. So only now catching up on this.

Adding `run_exports` seems reasonable.

Some kind of repodata patch is needed. Commented there on how we might approach that.

**Comment by jakirkham** [comment]
AFAICT this has been addressed. Going to close this out. Please feel free to reopen if I've missed something. Thanks all! 🙏
