### ISSUE TITLE
cuda-python: Support CUDA 12

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cuda-python-feedstock#31]
Depends on issue ( https://github.com/conda-forge/staged-recipes/issues/21382 )

**Comment by bdice** [comment]
We specifically need nvrtc and cudart per this comment: https://github.com/NVIDIA/cuda-python/issues/43#issuecomment-1449047410

Tracking those:
- https://github.com/conda-forge/staged-recipes/pull/21723
- https://github.com/conda-forge/staged-recipes/pull/21951

**Comment by leofang** [comment]
@bdice I actually don't understand why `cudart` is listed here. CUDA Python reimplemented cudart instead of dlopen'ing libcudart. I still think `nvrtc` is the only blocker.

**Comment by bdice** [comment]
@leofang Let's keep that discussion on the existing issue https://github.com/NVIDIA/cuda-python/issues/43. I'd like to use what has been agreed upon there. It's already vastly smaller than depending on the entire `cuda-toolkit` so I'm satisfied with the outcome.
