### ISSUE TITLE
Use cross-compilation instead

### ISSUE THREAD

**Issue by leofang** [conda-forge/cuda-python-feedstock#34]
This will significantly increase the build speed for aarch64/ppc64le. I've made a few attempts to understand how it works
- https://github.com/conda-forge/nccl-feedstock/pull/88 (pure C++ & CUDA)
- https://github.com/conda-forge/cupy-feedstock/pull/197 (python with C++ & CUDA extension modules)

**Comment by leofang** [comment]
Additional note: Luckily we no longer need to worry about CUDA Python 11.x, because for CUDA 11.x CF only supports cross compiling with CUDA 11.2, which would be an issue for CUDA Python (we need the latest headers).

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
The lack of splayed layout support in `cuda-python` ( https://github.com/NVIDIA/cuda-python/issues/46 ) will complicate making this change

More details in comment: https://github.com/conda-forge/cuda-python-feedstock/pull/58#issuecomment-1862099459
