### ISSUE TITLE
Missing `run_exports`?

### ISSUE THREAD

**Issue by leofang** [conda-forge/cuda-python-feedstock#9]
When CUDA Python is used as a built time dependency, I think the same version should be exported as the runtime dependency.

**Comment by leofang** [comment]
cc: @conda-forge/cuda-python

**Comment by jakirkham** [comment]
Sorry not following, why should that be the case? `run_exports` is typically used to constrain libraries that get linked to (like `zlib`). Not aware of linking happening with `cuda-python`.

In the rare cases where there is linking to a Python library (like `numpy`), the typical advice is to use `pin_compatible` in the dependency (for [example]( https://github.com/conda-forge/scipy-feedstock/blob/a12ad0db99d9d08be564289f4f8c97cf860c561b/recipe/meta.yaml#L68 )).

**Comment by leofang** [comment]
You're right. Thanks for reminder, John. The NumPy doc also mentioned the same approach:
https://numpy.org/devdocs/user/depending_on_numpy.html?highlight=downstream#build-time-dependency
